name: gw
services:
  nginx-proxy:
    build: ../../docker_file/nginx_compose
    ports:
      - "9889:80"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M

  scg-proxy:
    image: datamario24/sc-gateway:0.5.1
    ports:
      - "9000:9000"
    depends_on:
      - sc-eureka
    environment:
      - HELLO_SERVICE_URI=http://172.31.33.214:9001
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://sc-eureka:8765/eureka

  sc-eureka:
    image: datamario24/sc-eureka:0.1.0
    container_name: sc-eureka
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://sc-eureka:8765/eureka

